name: build-image

on:
  workflow_run:
    workflows: ["scan"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli curl

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t basic-blog:latest .

      - name: Run Trivy scan on Docker image
        run: |
          echo "Running Trivy scan on Docker image"
          curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -
          export PATH=$PATH:$(pwd)/bin
          trivy image --exit-code 0 --severity HIGH,CRITICAL basic-blog:latest || true
          trivy image --format json --output trivy-results.json basic-blog:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Log in to Amazon ECR
        run: |
          echo "Logging in to Amazon ECR..."
          echo aws-region
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image to ECR..."
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_TAG="basic-blog:$TIMESTAMP"
          docker tag basic-blog:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/$IMAGE_TAG
          echo "TF_VAR_image_uri=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/$IMAGE_TAG" >> build.env

      - name: Upload build.env as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-env
          path: build.env