name: update main.tf

on:
  workflow_run:
    workflows: ["fetch-outputs"]
    branches: [main]
    types: 
      - completed

jobs:
  update-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"

      - name: Load environment variables
        run: |
          echo "Loading environment variables..."
          echo "Contents of build.env:"
          cat build.env || echo "build.env not found"
          echo "Contents of terraform_outputs.env:"
          cat terraform_outputs.env || echo "terraform_outputs.env not found"
          export $(cat build.env | xargs)
          export $(cat terraform_outputs.env | xargs)

      - name: Clone repository
        run: |
          echo "Cloning repository..."
          git clone https://github.com/your-username/your-repo.git || exit 1
          cd your-repo

      - name: Create/Update TF_vars file
        run: |
          echo "Creating/Updating TF_vars file..."
          cat << EOF > terraform.tfvars
          image_uri = "${TF_VAR_image_uri}"
          public_subnet_ids = ${PUBLIC_SUBNET_IDS}
          alb_sg_id = "${ALB_SG_ID}"
          container_sg_id = "${CONTAINER_SG_ID}"
          vpc_id = "${VPC_ID}"
          EOF

      - name: Commit and push changes
        run: |
          git add terraform.tfvars
          git commit -m "Update image URI and Terraform outputs in TF_vars [ci skip]" || echo "No changes to commit"
          TAG_NAME="$(date +%Y.%m.%d-%H%M%S)"
          echo "Creating a new tag $TAG_NAME"
          git tag -a $TAG_NAME -m "Release version $TAG_NAME [ci skip]"
          git push origin HEAD:main --tags || exit 1